name: Publish to Central Repository
author: Samuel Meuli
description: Publishes the Maven project to the Central Repository

inputs:
  sonatype_secrets:
    description: Secret-string for Sonatype OSSRH (OSS Repository Hosting)
    required: true
  release_version:
    description: Version to set in pom before deploy
    required: true
  perform_release:
    description: Perform actual release
    required: true
    default: true

runs:
  using: docker
  image: Dockerfile
  env:
    SONATYPE_SECRETS: ${{ inputs.sonatype_secrets }}
    RELEASE_VERSION: ${{ inputs.release_version }}
    PERFORM_RELEASE: ${{ inputs.perform_release }}

branding:
  icon: upload-cloud
  color: orange
