name: Publish to Central Repository
author: Samuel Meuli
description: Publishes the Maven project to the Central Repository

inputs:
  gpg_private_key:
    description: base64-encoded GPG private key for signing the published artifacts
    required: true
  gpg_passphrase:
    description: Passphrase for the GPG key
    required: true
  ossrh_username:
    description: Username for Sonatype OSSRH (OSS Repository Hosting)
    required: true
  ossrh_password:
    description: Password for Sonatype OSSRH (OSS Repository Hosting)
    required: true
  release_version:
    description: Version to set in pom before deploy
    required: true

runs:
  using: docker
  image: Dockerfile
  env:
    GPG_PRIVATE_KEY: ${{ inputs.gpg_private_key }}
    GPG_PASSPHRASE: ${{ inputs.gpg_passphrase }}
    OSSRH_USERNAME: ${{ inputs.ossrh_username }}
    OSSRH_PASSWORD: ${{ inputs.ossrh_password }}
    RELEASE_VERSION: ${{ inputs.release_version }}

branding:
  icon: upload-cloud
  color: orange
